# Archivo de configuración para Dependabot
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "mauriciosobarzo"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"] 